### ISSUE TITLE
Error: Cannot refresh Falcon Container image: Cannot find suitable secret in namespace falcon-system-configure to push falcon-image to the registry

### ISSUE THREAD

**Issue by yakeeliuliu** [CrowdStrike/falcon-operator#104] opened 2021-10-15 16:03 UTC
**Hi, I got this error after the deployment:**

$ kubectl get falconcontainers.falcon.crowdstrike.com
NAME      STATUS   VERSION   ERROR
default      DONE                         Cannot refresh Falcon Container image: Cannot find suitable secret in namespace falcon-system-configure to push falcon-image to the registry

**More information from the yaml:**

 status:
    conditions:
    - lastTransitionTime: "2021-10-15T15:32:15Z"
      message: ""
      reason: Starting
      status: Unknown
      type: ImageReady
    - lastTransitionTime: "2021-10-15T15:32:15Z"
      message: ""
      reason: Starting
      status: Unknown
      type: InstallerComplete
    - lastTransitionTime: "2021-10-15T15:32:15Z"
      message: ""
      reason: Starting
      status: Unknown
      type: Complete
    errormsg: 'Cannot refresh Falcon Container image: Cannot find suitable secret
      in namespace falcon-system-configure to push falcon-image to the registry'
    phase: DONE
    retry_attempt: 5
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

Could you help with this ?

**Comment by isimluk** [comment] 2021-11-10 16:13
Hello @yakeeliuliu,

I am sorry, I have missed your issue report.

This issue is caused by the operator requiring push permissions to your registry. The operator will download Falcon Container image from CrowdStrike registry and mirror it locally to your registry for that it needs push permissions/secret. What registry do you use?

**Comment by isimluk** [comment] 2022-02-28 14:15
I am closing this issue as I cannot reproduce and cannot get my hands on the original issue at hand.

In the mean time, the robustness of the secrets handling has been improved significantly. A lot of information is available in the documentation at https://github.com/CrowdStrike/falcon-operator/tree/main/docs/container 

If you encounter this or other issue, please don't hesitate and create an issue like this one. Thanks!

**Closed by isimluk** 2022-02-28 14:15 UTC
